/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package common.gui;

import java.awt.event.WindowEvent;
import vehicle.gui.VehicleHome;

/**
 *
 * @author Sakib
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form ModuleSelection
     */
    public Home() {
        initComponents();
        this.setSize(600,560);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userManagementbtn = new javax.swing.JButton();
        customerAccountbtn = new javax.swing.JButton();
        vehicleRecordsbtn = new javax.swing.JButton();
        diagnosisAndRepairsbtn = new javax.swing.JButton();
        partsbtn = new javax.swing.JButton();
        specialistRepairsbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        homeMenu = new javax.swing.JMenu();
        custMenu = new javax.swing.JMenu();
        vehicleMenu = new javax.swing.JMenu();
        bookingMenu = new javax.swing.JMenu();
        partsMenu = new javax.swing.JMenu();
        SPCMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Module Selection");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userManagementbtn.setText("User Management");
        userManagementbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userManagementbtnActionPerformed(evt);
            }
        });
        getContentPane().add(userManagementbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 210, 50));

        customerAccountbtn.setText("Customer Account");
        customerAccountbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerAccountbtnActionPerformed(evt);
            }
        });
        getContentPane().add(customerAccountbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 210, 50));

        vehicleRecordsbtn.setText("Vehicle Records");
        vehicleRecordsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleRecordsbtnActionPerformed(evt);
            }
        });
        getContentPane().add(vehicleRecordsbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 210, 50));

        diagnosisAndRepairsbtn.setText("Diagnosis & Repair Bookings");
        diagnosisAndRepairsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diagnosisAndRepairsbtnActionPerformed(evt);
            }
        });
        getContentPane().add(diagnosisAndRepairsbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 210, 50));

        partsbtn.setText("Parts");
        partsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partsbtnActionPerformed(evt);
            }
        });
        getContentPane().add(partsbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 210, 50));

        specialistRepairsbtn.setText("Specialist Repairs");
        specialistRepairsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specialistRepairsbtnActionPerformed(evt);
            }
        });
        getContentPane().add(specialistRepairsbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 210, 50));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setText("Please Select an Option:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        homeMenu.setText("Homepage");
        homeMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMenuMouseClicked(evt);
            }
        });
        jMenuBar.add(homeMenu);

        custMenu.setText("Customer Account");
        custMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                custMenuMouseClicked(evt);
            }
        });
        custMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custMenuActionPerformed(evt);
            }
        });
        jMenuBar.add(custMenu);

        vehicleMenu.setText("Vehicle Records");
        vehicleMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vehicleMenuMouseClicked(evt);
            }
        });
        jMenuBar.add(vehicleMenu);

        bookingMenu.setText("Diagnosis & Repair Bookings");
        bookingMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookingMenuMouseClicked(evt);
            }
        });
        jMenuBar.add(bookingMenu);

        partsMenu.setText("Parts");
        partsMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                partsMenuMouseClicked(evt);
            }
        });
        jMenuBar.add(partsMenu);

        SPCMenu.setText("Specialist Repairs");
        SPCMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SPCMenuMouseClicked(evt);
            }
        });
        jMenuBar.add(SPCMenu);

        setJMenuBar(jMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customerAccountbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerAccountbtnActionPerformed
        close();
        customers.GUI.CustomerAccount Info = new customers.GUI.CustomerAccount();
        Info.setVisible(true);
    }//GEN-LAST:event_customerAccountbtnActionPerformed

    private void userManagementbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userManagementbtnActionPerformed
        close();
        vehicle.gui.VehicleQuickAdd Info = new vehicle.gui.VehicleQuickAdd();
       Info.setVisible(true);
    }//GEN-LAST:event_userManagementbtnActionPerformed

    private void vehicleRecordsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleRecordsbtnActionPerformed
        VehicleHome vehicleHome = new VehicleHome();
        vehicleHome.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_vehicleRecordsbtnActionPerformed

    private void diagnosisAndRepairsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diagnosisAndRepairsbtnActionPerformed
        diagRep.gui.BookingHomepage bookingHome = new diagRep.gui.BookingHomepage();
        bookingHome.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_diagnosisAndRepairsbtnActionPerformed

    private void partsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partsbtnActionPerformed
        parts.gui.PartsHome partsHome = new parts.gui.PartsHome();
        partsHome.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_partsbtnActionPerformed

    private void specialistRepairsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specialistRepairsbtnActionPerformed
        close();
        specRep.gui.specialistRepairGUI Info = new specRep.gui.specialistRepairGUI();
       Info.setVisible(true);
    }//GEN-LAST:event_specialistRepairsbtnActionPerformed

    private void homeMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMenuMouseClicked
        common.gui.Home homepage = new common.gui.Home();
        homepage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeMenuMouseClicked

    private void custMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_custMenuMouseClicked
        customers.GUI.CustomerHome custHome = new customers.GUI.CustomerHome();
        custHome.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_custMenuMouseClicked

    private void custMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custMenuActionPerformed

    }//GEN-LAST:event_custMenuActionPerformed

    private void vehicleMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vehicleMenuMouseClicked
        vehicle.gui.VehicleHome indV = new vehicle.gui.VehicleHome();
        indV.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_vehicleMenuMouseClicked

    private void bookingMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingMenuMouseClicked
        diagRep.gui.BookingHomepage bookingHome = new diagRep.gui.BookingHomepage();
        bookingHome.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bookingMenuMouseClicked

    private void partsMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_partsMenuMouseClicked
        parts.gui.PartsHome partsHome = new parts.gui.PartsHome();
        partsHome.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_partsMenuMouseClicked

    private void SPCMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SPCMenuMouseClicked
        specRep.gui.SPCHome SPCHome = new specRep.gui.SPCHome();
        SPCHome.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_SPCMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu SPCMenu;
    private javax.swing.JMenu bookingMenu;
    private javax.swing.JMenu custMenu;
    private javax.swing.JButton customerAccountbtn;
    private javax.swing.JButton diagnosisAndRepairsbtn;
    private javax.swing.JMenu homeMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu partsMenu;
    private javax.swing.JButton partsbtn;
    private javax.swing.JButton specialistRepairsbtn;
    private javax.swing.JButton userManagementbtn;
    private javax.swing.JMenu vehicleMenu;
    private javax.swing.JButton vehicleRecordsbtn;
    // End of variables declaration//GEN-END:variables

    private void close() {
        WindowEvent exit = new WindowEvent(this,WindowEvent.WINDOW_CLOSING); //To change body of generated methods, choose Tools | Templates.
    }
}
