/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package common.gui;

import javax.swing.JOptionPane;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
/**
/**
 *
 * @author Sakib
 */
public class Login extends javax.swing.JFrame {
Connection connection = null;
   PreparedStatement pst = null;
   ResultSet rs = null;
    
    
    
    public Login() {
        initComponents();
        this.setSize(600,400);
        this.setLocationRelativeTo(null);
        
           try {
            // db parameters
            
            String url = "jdbc:sqlite:../SE16/Master/Documents/Database.db";

            // create a connection to the Database
            connection = DriverManager.getConnection(url);
            
            System.out.println("Connection to SQLite has been established.");
            
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        signinbtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GMSIS Authentication");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel1.setText("Login");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

        jLabel2.setText("Username:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 256, -1));

        jLabel3.setText("Password:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 71, -1));

        signinbtn.setText("Sign In");
        signinbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signinbtnMouseClicked(evt);
            }
        });
        signinbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinbtnActionPerformed(evt);
            }
        });
        getContentPane().add(signinbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 141, 41));

        jButton2.setText("Clear Fields");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 141, 41));

        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
        });
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 256, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       jTextField1.setText(null);
        jPasswordField1.setText(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void signinbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinbtnActionPerformed
      String sql = "SELECT * FROM LoginUsers WHERE ID=? AND Password=?";
      //adjust so regular users cannot delete users
       try {
                pst=connection.prepareStatement(sql);
                pst.setString(1, jTextField1.getText());
                pst.setString(2, jPasswordField1.getText());
                
                rs=pst.executeQuery();
                if(rs.next()) {
                    JOptionPane.showMessageDialog(null, "Login Successful");
                    close();
                    
                            String user = rs.getString("UserType");
                    
                    if(user.equals("Administrator")) {
                          Home Info = new Home();
        Info.setVisible(true);
                    }
                    
                    else {
                    
       Home Info = new Home();
        Info.setVisible(true);
                }
                             
                }
                
                else {
                    JOptionPane.showMessageDialog(null, "Login failed, please try again");
                }
                
                
             } 
              catch (Exception e) {
                  JOptionPane.showMessageDialog(null, e);
              }
             
             finally{ 
            try{ 
                pst.close(); 
                rs.close(); 
            }catch(Exception e){ 
            }
        }
             
    }//GEN-LAST:event_signinbtnActionPerformed

    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed
       
      
         String sql = "SELECT * FROM LoginUsers WHERE ID=? AND Password=?";
          if(evt.getKeyCode()==KeyEvent.VK_ENTER) 
       
        
      //adjust so regular users cannot delete users
     
             try {
                pst=connection.prepareStatement(sql);
                pst.setString(1, jTextField1.getText());
                pst.setString(2, jPasswordField1.getText());
                
                rs=pst.executeQuery();
                if(rs.next()) {
                    JOptionPane.showMessageDialog(null, "Login Successful");
                    close();
                    
                            String user = rs.getString("UserType");
                    
                    if(user.equals("Administrator")) {
                        Home Info = new Home();
                        Info.setVisible(true);
                    }
                    
                    else {
                    
        Home Info = new Home();
        Info.setVisible(true);
                }
                             
                }
                
                else {
                    JOptionPane.showMessageDialog(null, "Login failed, please try again");
                }
                
                
             } 
              catch (Exception e) {
                  JOptionPane.showMessageDialog(null, e);
              }
             
             finally{ 
            try{ 
                pst.close(); 
                rs.close(); 
            }catch(Exception e){ 
            }
        }
             
               
            
    }//GEN-LAST:event_jPasswordField1KeyPressed

    private void signinbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signinbtnMouseClicked
           
    }//GEN-LAST:event_signinbtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton signinbtn;
    // End of variables declaration//GEN-END:variables

    private void close() {
        WindowEvent exit = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
    }
}
