package common.gui;

import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Mohammed
 */
public class Users extends javax.swing.JFrame {
Connection connection = null;
   PreparedStatement pst = null;
   ResultSet rs = null;
   
    public Users() {
        initComponents();
         try {
            // db parameters
            
            String url = "jdbc:sqlite:Master/Documents/Database.db";

            // create a connection to the Database
            connection = DriverManager.getConnection(url);
            
            System.out.println("Connection to SQLite has been established.");
            
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        } 
        
        
       Update_table();
         }
    
          private void Update_table () {
      
       
       
        
        
        try {
           String sql = "SELECT * FROM LoginUsers";
            pst = connection.prepareStatement(sql);
            rs = pst.executeQuery();
         jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        
        }
         catch (SQLException e)
        {
            System.out.println( e.getMessage() );
        }
        
  } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu8 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(746, 0, 377, 574));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("User Management");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 23, -1, -1));

        jLabel2.setText("Search by ID/Forename/Surname:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 88, -1, -1));

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 83, 374, -1));

        jLabel3.setText("ID:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 167, -1, -1));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 162, 149, -1));

        jLabel4.setText("Forename:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 199, -1, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 194, 149, -1));

        jLabel5.setText("Surname:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 232, -1, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 227, 150, -1));

        jLabel6.setText("Password:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(491, 167, -1, -1));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 162, 143, -1));

        jLabel7.setText("User Type:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(491, 198, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrator", "User" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 194, -1, -1));

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 332, 111, -1));

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 332, 111, -1));

        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 332, 110, -1));

        jMenu8.setText("Customer Account");
        jMenu8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu8MouseClicked(evt);
            }
        });
        jMenu8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu8ActionPerformed(evt);
            }
        });
        jMenuBar2.add(jMenu8);

        jMenu1.setText("Vehicle Records");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Diagnosis & Repair Bookings");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Parts");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Specialist Repairs");
        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu8MouseClicked
        close();
        customers.GUI.CustomerAccount Info = new customers.GUI.CustomerAccount();
        Info.setVisible(true);
    }//GEN-LAST:event_jMenu8MouseClicked

    private void jMenu8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu8ActionPerformed

    }//GEN-LAST:event_jMenu8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            int id = Integer.parseInt(jTextField2.getText());
            
            String forename = jTextField3.getText();
            String surname = jTextField4.getText();
            String password = jTextField5.getText();
            String usertype = (String) jComboBox1.getSelectedItem();
            
            String sql = "INSERT INTO LoginUsers (`ID`,`Password`,`Forename`, `Surname`, `UserType`) VALUES ('"+id +"', '"+password +"', '"+forename +"', '"+surname +"', '"+usertype +"');";
           pst = connection.prepareStatement(sql);
           pst.execute(); 
            
            
           
        }
catch (Exception e) {
    JOptionPane.showMessageDialog(null, e);
}
        
        finally{ 
            try{ 
                pst.close(); 
                rs.close(); 
            }catch(Exception e){ 
            }
        }
        
        
        Update_table();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        
        try {
                 
           String search = jTextField1.getText();
            String sql = "select * from LoginUsers where Forename=? or Surname=? or ID=?"  ;
          
            pst = connection.prepareStatement(sql);
           pst.setString(1, search);
            pst.setString(2, search);
           pst.setString(3, search);
            rs = pst.executeQuery();
        
             
        if(rs.next()) {
            
            String add = rs.getString("Forename");
            jTextField3.setText(add);
            String add1 = rs.getString("Surname");
            jTextField4.setText(add1);
            int add2 = rs.getInt("ID");
             jTextField2.setText(String.valueOf(add2));
            String add3 = rs.getString("Password");
            jTextField5.setText(add3);
            String add4 = rs.getString("UserType");
           jComboBox1.setSelectedItem(add4);
        }
        }
           catch (Exception e)
        {
           JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete?", "Delete", JOptionPane.YES_NO_CANCEL_OPTION);
        if(p==0) {
            
            try {
            
             int row = jTable1.getSelectedRow();
            String tableclick =(jTable1.getModel().getValueAt(row, 0).toString());
            
            //pst.setInt(1, Integer.parseInt(jTextField8.getText()));
        //pst.setString(1, jTextField8.getText());
          String sql = "Delete from LoginUsers where ID ='"+tableclick+"' ";
            
          pst = connection.prepareStatement(sql);  
          pst.execute();
           JOptionPane.showMessageDialog(null, "User Deleted");
              
        }
        catch (Exception e) {
         JOptionPane.showMessageDialog(null, e);
        }
        finally{ 
            try{ 
                pst.close(); 
                rs.close(); 
            }catch(Exception e){ 
            }
        }
        
        
        
        Update_table();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try {
             int row = jTable1.getSelectedRow();
         String click = (jTable1.getModel().getValueAt(row,0).toString());
          
         String sql = "SELECT * FROM LoginUsers WHERE ID='"+click+"' ";
         pst = connection.prepareStatement(sql);
            rs=pst.executeQuery();
            
            if(rs.next()) {
                String add = rs.getString("Forename");
            jTextField3.setText(add);
            String add1 = rs.getString("Surname");
            jTextField4.setText(add1);
            int add2 = rs.getInt("ID");
             jTextField2.setText(String.valueOf(add2));
            String add3 = rs.getString("Password");
            jTextField5.setText(add3);
            String add4 = rs.getString("UserType");
           jComboBox1.setSelectedItem(add4);
            }
            
            
            
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            String id = jTextField2.getText();
            String forename = jTextField3.getText();
            String surname = jTextField4.getText();
            String password = jTextField5.getText();
            String type = (String) jComboBox1.getSelectedItem();
            
            String sql = "UPDATE LoginUsers SET ID='"+id+"', Password='"+password+"', Forename='"+forename+"', Surname='"+surname+"', UserType='"+type+"' WHERE ID='"+id+"'  ";
            pst=connection.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Updated");
            
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
         finally{ 
            try{ 
                pst.close(); 
                rs.close(); 
            }catch(Exception e){ 
            }
        }
        
        Update_table();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Users().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
  private void close() {
       WindowEvent exit = new WindowEvent(this,WindowEvent.WINDOW_CLOSING); //To change body of generated methods, choose Tools | Templates.
     //  Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(exit);
    }


}





